"""Launch catalog: themed word-search packs (English-first, Riddlewood).

Each theme -> one sellable pack of 10 puzzles. Word lists curated for
mass-appeal, giftable, evergreen Etsy niches. Colors are dark (light text
on cover). Consumed by build_all.py.
"""
from wordsearch import Puzzle

THEMES = [
    {
        "slug": "coffee-lovers-word-search",
        "title": "Coffee Lover's Word Search",
        "subtitle": "Cozy puzzles for people who run on coffee",
        "color": (59, 41, 33),
        "puzzles": [
            Puzzle("Coffee Drinks", ["ESPRESSO", "LATTE", "CAPPUCCINO", "MOCHA", "MACCHIATO", "AMERICANO", "CORTADO", "FLATWHITE", "RISTRETTO", "AFFOGATO", "DOPPIO", "CACAO"]),
            Puzzle("Brewing Methods", ["FRENCHPRESS", "POUROVER", "AEROPRESS", "MOKA", "DRIP", "SIPHON", "COLDBREW", "PERCOLATOR", "CHEMEX", "STEEP", "FILTER", "KETTLE"]),
            Puzzle("Cafe Vibes", ["AROMA", "BARISTA", "CREMA", "FOAM", "MUG", "BEANS", "ROAST", "GRINDER", "STEAM", "COZY", "REFILL", "CAFFEINE"]),
            Puzzle("Coffee Around The World", ["ITALY", "ETHIOPIA", "COLOMBIA", "BRAZIL", "VIENNA", "TURKISH", "CUBANO", "IRISH", "VIETNAM", "KENYA", "GUATEMALA", "JAVA"]),
            Puzzle("Coffee And Sweets", ["BISCOTTI", "CROISSANT", "TIRAMISU", "MUFFIN", "BROWNIE", "DONUT", "COOKIE", "SCONE", "CARAMEL", "VANILLA", "CINNAMON", "HAZELNUT"]),
            Puzzle("Espresso Bar", ["SHOT", "CREMA", "TAMPER", "PORTAFILTER", "GROUP", "DOSE", "GRIND", "EXTRACTION", "PUCK", "PITCHER", "MILK", "STEAMER"]),
            Puzzle("Morning Ritual", ["WAKEUP", "SUNRISE", "STRETCH", "KETTLE", "BREW", "POUR", "SIP", "NEWSPAPER", "JOURNAL", "QUIET", "ROUTINE", "FRESH"]),
            Puzzle("Coffee Flavors", ["VANILLA", "CARAMEL", "HAZELNUT", "MOCHA", "PUMPKIN", "CINNAMON", "TOFFEE", "CHOCOLATE", "COCONUT", "ALMOND", "MAPLE", "NUTMEG"]),
            Puzzle("Coffee Gear", ["GRINDER", "KETTLE", "SCALE", "TAMPER", "FILTER", "CARAFE", "FROTHER", "THERMOS", "PRESS", "BREWER", "SPOON", "MUG"]),
            Puzzle("Coffee Shop", ["MENU", "BARISTA", "COUNTER", "PASTRY", "LOUNGE", "ORDER", "LATTE", "TIPJAR", "BEANS", "BREW", "REGULAR", "STOOL"]),
        ],
    },
    {
        "slug": "cat-lovers-word-search",
        "title": "Cat Lover's Word Search",
        "subtitle": "Purr-fect puzzles for cat people",
        "color": (45, 40, 58),
        "puzzles": [
            Puzzle("Cat Breeds", ["SIAMESE", "PERSIAN", "BENGAL", "RAGDOLL", "SPHYNX", "MAINECOON", "ABYSSINIAN", "BURMESE", "TABBY", "MANX", "BIRMAN", "SAVANNAH"]),
            Puzzle("Cat Behavior", ["PURR", "KNEAD", "POUNCE", "GROOM", "ZOOMIES", "STALK", "CURIOUS", "NAP", "SCRATCH", "MEOW", "HISS", "CUDDLE"]),
            Puzzle("Kitten Things", ["TINY", "PLAYFUL", "FLUFFY", "WHISKERS", "PAWS", "MITTENS", "YARN", "BASKET", "MILK", "SLEEPY", "CURIOUS", "SOFT"]),
            Puzzle("Cat Toys", ["YARN", "MOUSE", "FEATHER", "LASER", "BALL", "STRING", "TUNNEL", "CATNIP", "SCRATCHER", "WAND", "PUZZLE", "BELL"]),
            Puzzle("Famous Cats", ["GARFIELD", "FELIX", "SYLVESTER", "HELLOKITTY", "GRUMPY", "SIMBA", "CHESHIRE", "AZRAEL", "SALEM", "SNOWBELL", "TOM", "NYAN"]),
            Puzzle("Cat Care", ["GROOMING", "BRUSHING", "LITTER", "FEEDING", "WATER", "VACCINE", "COLLAR", "SCRATCHPOST", "PLAY", "CHECKUP", "NAILS", "VET"]),
            Puzzle("Cat Anatomy", ["WHISKERS", "PAWS", "TAIL", "EARS", "CLAWS", "NOSE", "EYES", "TONGUE", "BELLY", "PADS", "FANGS", "FUR"]),
            Puzzle("Cat Sounds", ["MEOW", "PURR", "HISS", "CHIRP", "TRILL", "GROWL", "YOWL", "MURMUR", "CHATTER", "SQUEAK", "SNORE", "MEW"]),
            Puzzle("Cat Naps", ["SUNBEAM", "WINDOWSILL", "BLANKET", "CUSHION", "CURLED", "COZY", "DREAM", "SNOOZE", "LAP", "BASKET", "WARM", "SOFT"]),
            Puzzle("Popular Cat Names", ["LUNA", "MILO", "OLIVER", "BELLA", "CHLOE", "SIMBA", "NALA", "TIGER", "SHADOW", "PUMPKIN", "GINGER", "LEO"]),
        ],
    },
    {
        "slug": "garden-word-search",
        "title": "In The Garden Word Search",
        "subtitle": "Relaxing puzzles for green thumbs",
        "color": (30, 58, 42),
        "puzzles": [
            Puzzle("Garden Flowers", ["ROSE", "TULIP", "DAISY", "LILY", "PEONY", "DAHLIA", "SUNFLOWER", "MARIGOLD", "LAVENDER", "IRIS", "POPPY", "ZINNIA"]),
            Puzzle("Vegetables", ["TOMATO", "CARROT", "LETTUCE", "PEPPER", "ONION", "ZUCCHINI", "SPINACH", "RADISH", "CUCUMBER", "BEAN", "POTATO", "KALE"]),
            Puzzle("Herbs", ["BASIL", "THYME", "ROSEMARY", "MINT", "PARSLEY", "SAGE", "OREGANO", "CILANTRO", "CHIVE", "DILL", "FENNEL", "TARRAGON"]),
            Puzzle("Garden Tools", ["SHOVEL", "RAKE", "TROWEL", "HOE", "PRUNER", "GLOVES", "WATERINGCAN", "WHEELBARROW", "SPADE", "SHEARS", "FORK", "HOSE"]),
            Puzzle("Trees", ["OAK", "MAPLE", "PINE", "BIRCH", "WILLOW", "CEDAR", "ELM", "CHERRY", "MAGNOLIA", "ASPEN", "BEECH", "SPRUCE"]),
            Puzzle("Backyard Birds", ["ROBIN", "SPARROW", "FINCH", "CARDINAL", "BLUEJAY", "WREN", "CHICKADEE", "DOVE", "STARLING", "SWALLOW", "MAGPIE", "THRUSH"]),
            Puzzle("Garden Pests", ["APHID", "SLUG", "SNAIL", "BEETLE", "CATERPILLAR", "WEEVIL", "MITE", "GRUB", "EARWIG", "WHITEFLY", "MOLE", "THRIP"]),
            Puzzle("Planting", ["SEED", "SOIL", "COMPOST", "MULCH", "SPROUT", "SAPLING", "WATER", "SUNLIGHT", "TRANSPLANT", "BULB", "ROOT", "GROW"]),
            Puzzle("Garden Wildlife", ["BEE", "BUTTERFLY", "LADYBUG", "HEDGEHOG", "FROG", "WORM", "DRAGONFLY", "SQUIRREL", "SNAIL", "TOAD", "BEETLE", "MOTH"]),
            Puzzle("Garden Tasks", ["WEEDING", "PRUNING", "WATERING", "SOWING", "HARVEST", "MULCHING", "DIGGING", "RAKING", "PLANTING", "TRIMMING", "COMPOST", "POTTING"]),
        ],
    },
    {
        "slug": "self-care-word-search",
        "title": "Self-Care & Calm Word Search",
        "subtitle": "Gentle puzzles to slow down and unwind",
        "color": (54, 46, 68),
        "puzzles": [
            Puzzle("Calm Words", ["PEACE", "BREATHE", "STILL", "QUIET", "GENTLE", "EASE", "RELAX", "SOOTHE", "TRANQUIL", "SERENE", "SOFTEN", "REST"]),
            Puzzle("Self Care", ["REST", "HYDRATE", "JOURNAL", "WALK", "NOURISH", "PAUSE", "UNPLUG", "SLEEP", "STRETCH", "BOUNDARIES", "BATH", "BREATHE"]),
            Puzzle("Meditation", ["BREATH", "MANTRA", "STILLNESS", "FOCUS", "PRESENCE", "BALANCE", "CALM", "AWARENESS", "SILENCE", "POSTURE", "MINDFUL", "ZEN"]),
            Puzzle("Cozy Evening", ["BLANKET", "CANDLE", "TEA", "BOOK", "SLIPPERS", "FIREPLACE", "PLAYLIST", "PAJAMAS", "WARMTH", "SOFA", "DIM", "HUSH"]),
            Puzzle("Positive Vibes", ["GRATITUDE", "JOY", "HOPE", "KINDNESS", "SMILE", "GROWTH", "COURAGE", "LIGHT", "THRIVE", "BLOOM", "SHINE", "TRUST"]),
            Puzzle("Spa Day", ["MASSAGE", "FACIAL", "AROMATHERAPY", "SAUNA", "SOAK", "SCRUB", "LOTION", "ROBE", "CUCUMBER", "STEAM", "RELAX", "GLOW"]),
            Puzzle("Gratitude", ["THANKFUL", "BLESSED", "APPRECIATE", "PRESENT", "ABUNDANCE", "KINDNESS", "GIVING", "WARMTH", "HUMBLE", "JOYFUL", "NOTICE", "SAVOR"]),
            Puzzle("Slow Living", ["SIMPLE", "PRESENT", "UNHURRIED", "SAVOR", "MINDFUL", "NATURE", "PAUSE", "BALANCE", "INTENTION", "ENOUGH", "BREATHE", "LINGER"]),
            Puzzle("Breathe", ["INHALE", "EXHALE", "DEEP", "SLOW", "PAUSE", "RHYTHM", "CALM", "RELEASE", "FILL", "EMPTY", "STEADY", "FLOW"]),
            Puzzle("Comfort", ["WARM", "SOFT", "SAFE", "COZY", "HUG", "TEA", "BLANKET", "HOME", "GENTLE", "QUIET", "SOOTHE", "EMBRACE"]),
        ],
    },
    {
        "slug": "beach-summer-word-search",
        "title": "Beach & Summer Word Search",
        "subtitle": "Sunny puzzles for lazy summer days",
        "color": (28, 58, 74),
        "puzzles": [
            Puzzle("At The Beach", ["SAND", "WAVES", "SHELL", "TOWEL", "UMBRELLA", "SUNSCREEN", "BUCKET", "SANDCASTLE", "TIDE", "SURF", "BAREFOOT", "COVE"]),
            Puzzle("Summer Fun", ["BARBECUE", "PICNIC", "FIREWORKS", "CAMPING", "ROADTRIP", "FESTIVAL", "POOL", "HAMMOCK", "LEMONADE", "SUNGLASSES", "FRISBEE", "FERRY"]),
            Puzzle("Ocean Life", ["DOLPHIN", "CRAB", "STARFISH", "SEAWEED", "TURTLE", "JELLYFISH", "CORAL", "SEAHORSE", "OCTOPUS", "CLAM", "URCHIN", "WHALE"]),
            Puzzle("Beach Gear", ["TOWEL", "COOLER", "SANDALS", "GOGGLES", "SNORKEL", "FLOAT", "VISOR", "PARASOL", "TOTEBAG", "SURFBOARD", "CHAIR", "HAT"]),
            Puzzle("Tropical", ["PALM", "COCONUT", "HIBISCUS", "PINEAPPLE", "LAGOON", "MANGO", "PARROT", "SUNSET", "BREEZE", "ISLAND", "ORCHID", "HUMID"]),
            Puzzle("Ice Cream", ["VANILLA", "SUNDAE", "CONE", "SCOOP", "SPRINKLES", "SORBET", "GELATO", "POPSICLE", "CHERRY", "WAFFLE", "CARAMEL", "MINT"]),
            Puzzle("Summer Sports", ["SURFING", "SWIMMING", "VOLLEYBALL", "KAYAKING", "SAILING", "SNORKELING", "PADDLE", "DIVING", "CYCLING", "JOGGING", "TENNIS", "ROWING"]),
            Puzzle("Seaside Town", ["HARBOR", "PIER", "LIGHTHOUSE", "BOARDWALK", "FERRY", "MARINA", "SEAGULL", "ARCADE", "COTTAGE", "DOCK", "PROMENADE", "CAFE"]),
            Puzzle("Sunny Days", ["SUNSHINE", "WARMTH", "BLUESKY", "BREEZE", "PICNIC", "SHADE", "GLOW", "HORIZON", "BRIGHT", "HEAT", "LAZY", "TAN"]),
            Puzzle("Beach Picnic", ["BASKET", "SANDWICH", "LEMONADE", "WATERMELON", "CHIPS", "COOLER", "BLANKET", "NAPKIN", "GRAPES", "COOKIES", "THERMOS", "FRUIT"]),
        ],
    },
    {
        "slug": "christmas-word-search",
        "title": "Christmas Word Search",
        "subtitle": "Festive puzzles for the holiday season",
        "color": (74, 30, 38),
        "puzzles": [
            Puzzle("Christmas Words", ["SANTA", "SLEIGH", "REINDEER", "STOCKING", "TINSEL", "MISTLETOE", "CAROL", "ORNAMENT", "WREATH", "CHIMNEY", "GIFT", "JOY"]),
            Puzzle("All About Santa", ["BEARD", "SLEIGH", "WORKSHOP", "ELVES", "NORTHPOLE", "CHIMNEY", "LIST", "COOKIES", "MILK", "REDSUIT", "HOHOHO", "BELT"]),
            Puzzle("Holiday Treats", ["GINGERBREAD", "COOKIES", "FRUITCAKE", "EGGNOG", "CANDYCANE", "TRUFFLE", "HOTCOCOA", "PEPPERMINT", "PIE", "FUDGE", "TOFFEE", "ROAST"]),
            Puzzle("Winter", ["SNOW", "FROST", "ICICLE", "BLIZZARD", "MITTENS", "SCARF", "SLED", "FIREPLACE", "CHILL", "FLAKE", "SHIVER", "COCOA"]),
            Puzzle("Christmas Songs", ["JINGLEBELLS", "NOEL", "SILENTNIGHT", "CAROL", "SLEIGHRIDE", "FROSTY", "RUDOLPH", "DECKHALLS", "ANGELS", "HYMN", "JOYFUL", "STAR"]),
            Puzzle("Decorations", ["TREE", "LIGHTS", "GARLAND", "BAUBLE", "TINSEL", "WREATH", "STAR", "RIBBON", "CANDLE", "STOCKING", "BELLS", "HOLLY"]),
            Puzzle("Gift Giving", ["PRESENT", "RIBBON", "WRAPPING", "BOW", "TAG", "SURPRISE", "GENEROSITY", "GIVING", "SECRETSANTA", "EXCHANGE", "JOY", "THANKS"]),
            Puzzle("Reindeer", ["RUDOLPH", "DASHER", "DANCER", "PRANCER", "VIXEN", "COMET", "CUPID", "DONNER", "BLITZEN", "ANTLERS", "SLEIGH", "HOOVES"]),
            Puzzle("Christmas Eve", ["STOCKING", "COOKIES", "FIREPLACE", "PAJAMAS", "STARRY", "HUSH", "BLANKET", "STORY", "WAITING", "COCOA", "DREAMS", "QUIET"]),
            Puzzle("Festive Feelings", ["MERRY", "JOLLY", "CHEER", "TWINKLE", "SPARKLE", "WARMTH", "FAMILY", "FEAST", "LAUGHTER", "GLOW", "COZY", "BRIGHT"]),
        ],
    },
    {
        "slug": "dog-lovers-word-search",
        "title": "Dog Lover's Word Search",
        "subtitle": "Pawsome puzzles for dog people",
        "color": (60, 50, 40),
        "puzzles": [
            Puzzle("Dog Breeds", ["LABRADOR", "POODLE", "BEAGLE", "BULLDOG", "BOXER", "DACHSHUND", "CHIHUAHUA", "HUSKY", "CORGI", "TERRIER", "PUG", "SPANIEL"]),
            Puzzle("Puppy Things", ["PLAYFUL", "FLUFFY", "PAWS", "LEASH", "TREATS", "FETCH", "WAGGING", "CUDDLES", "ZOOMIES", "CHEW", "TINY", "SLEEPY"]),
            Puzzle("Dog Toys", ["BALL", "FRISBEE", "ROPE", "SQUEAKY", "BONE", "CHEW", "TUGTOY", "PLUSH", "STICK", "KONG", "FETCH", "PUZZLE"]),
            Puzzle("At The Park", ["FETCH", "RUN", "LEASH", "FRIENDS", "SNIFF", "DIGGING", "FRISBEE", "SQUIRREL", "BENCH", "TRAIL", "SHADE", "SPLASH"]),
            Puzzle("Dog Care", ["GROOMING", "BRUSHING", "BATH", "WALKING", "FEEDING", "COLLAR", "TRAINING", "VACCINE", "NAILS", "TREATS", "CHECKUP", "VET"]),
            Puzzle("Famous Dogs", ["LASSIE", "SCOOBY", "SNOOPY", "BEETHOVEN", "BALTO", "PLUTO", "BOLT", "HACHIKO", "TOTO", "MARLEY", "CLIFFORD", "REX"]),
            Puzzle("Dog Commands", ["SIT", "STAY", "COME", "HEEL", "DOWN", "FETCH", "ROLL", "SHAKE", "SPEAK", "WAIT", "LEAVE", "PAW"]),
            Puzzle("Dog Sounds", ["BARK", "WOOF", "GROWL", "HOWL", "WHINE", "YELP", "PANT", "SNARL", "BAY", "GRUMBLE", "SNORE", "WHIMPER"]),
            Puzzle("Walkies", ["LEASH", "HARNESS", "COLLAR", "SIDEWALK", "PARK", "SNIFF", "MARKING", "PUDDLE", "TREATS", "POOPBAG", "TRAIL", "FRIENDS"]),
            Puzzle("Popular Dog Names", ["MAX", "BELLA", "CHARLIE", "LUNA", "COOPER", "LUCY", "ROCKY", "DAISY", "BUDDY", "MOLLY", "TEDDY", "RUBY"]),
        ],
    },
    {
        "slug": "halloween-word-search",
        "title": "Halloween Word Search",
        "subtitle": "Spooky puzzles for the Halloween season",
        "color": (52, 30, 12),
        "puzzles": [
            Puzzle("Halloween Words", ["PUMPKIN", "GHOST", "WITCH", "SPOOKY", "CANDY", "COSTUME", "HAUNTED", "SKELETON", "BAT", "SPIDER", "CAULDRON", "BROOM"]),
            Puzzle("Costumes", ["VAMPIRE", "WITCH", "ZOMBIE", "PIRATE", "GHOST", "MUMMY", "SUPERHERO", "SKELETON", "WIZARD", "CLOWN", "FAIRY", "ROBOT"]),
            Puzzle("Spooky Creatures", ["GHOST", "GOBLIN", "VAMPIRE", "WEREWOLF", "ZOMBIE", "SKELETON", "WITCH", "MUMMY", "BAT", "SPIDER", "GHOUL", "CREATURE"]),
            Puzzle("Trick Or Treat", ["CANDY", "COSTUME", "DOORBELL", "PUMPKIN", "BASKET", "SPOOKY", "NEIGHBORS", "TREATS", "LANTERN", "NIGHT", "CHOCOLATE", "GHOST"]),
            Puzzle("Haunted House", ["COBWEB", "CREAKING", "SHADOWS", "GHOST", "ATTIC", "DUSTY", "CANDLE", "SCREAM", "DARKNESS", "CRYPT", "SPIDER", "MOONLIGHT"]),
            Puzzle("Pumpkin Patch", ["PUMPKIN", "CARVING", "SEEDS", "VINE", "ORANGE", "LANTERN", "HARVEST", "GOURD", "FIELD", "PATCH", "STEM", "SCARECROW"]),
            Puzzle("Halloween Candy", ["CHOCOLATE", "LOLLIPOP", "CARAMEL", "GUMMY", "TOFFEE", "LICORICE", "CANDYCORN", "NOUGAT", "JELLYBEAN", "FUDGE", "SOUR", "MINT"]),
            Puzzle("Witchy Things", ["CAULDRON", "BROOM", "POTION", "SPELL", "HAT", "BLACKCAT", "WART", "CRYSTAL", "HERBS", "CHANT", "MOON", "RAVEN"]),
            Puzzle("Monster Mash", ["FRANKENSTEIN", "DRACULA", "WOLFMAN", "MUMMY", "ZOMBIE", "GHOUL", "CREATURE", "GREMLIN", "OGRE", "BEAST", "PHANTOM", "BLOB"]),
            Puzzle("Spooky Night", ["MOON", "FOG", "SHADOW", "OWL", "HOWL", "CHILL", "CREAK", "WHISPER", "LANTERN", "MIDNIGHT", "GRAVE", "MIST"]),
        ],
    },
    {
        "slug": "fall-thanksgiving-word-search",
        "title": "Fall & Thanksgiving Word Search",
        "subtitle": "Cozy autumn puzzles with full solutions",
        "color": (66, 40, 20),
        "puzzles": [
            Puzzle("Autumn Words", ["LEAVES", "PUMPKIN", "HARVEST", "ACORN", "SWEATER", "CIDER", "CRISP", "MAPLE", "BONFIRE", "ORANGE", "COZY", "CHILL"]),
            Puzzle("Fall Leaves", ["MAPLE", "OAK", "CRIMSON", "GOLDEN", "AMBER", "RUSTLE", "FALLING", "RAKE", "PILE", "CRUNCH", "SCARLET", "FOLIAGE"]),
            Puzzle("Thanksgiving", ["TURKEY", "STUFFING", "GRAVY", "PUMPKIN", "CRANBERRY", "FEAST", "FAMILY", "GRATITUDE", "PIE", "HARVEST", "YAMS", "BLESSING"]),
            Puzzle("Harvest Time", ["PUMPKIN", "CORN", "SQUASH", "APPLE", "WHEAT", "BARN", "HAYRIDE", "SCARECROW", "BUSHEL", "ORCHARD", "GOURD", "HARVEST"]),
            Puzzle("Cozy Fall", ["SWEATER", "BLANKET", "CIDER", "FIREPLACE", "CANDLE", "BOOTS", "SCARF", "PUMPKIN", "COCOA", "SOUP", "KNIT", "WARM"]),
            Puzzle("Fall Flavors", ["PUMPKIN", "CINNAMON", "NUTMEG", "APPLE", "MAPLE", "CARAMEL", "PECAN", "CLOVE", "GINGER", "VANILLA", "SPICE", "PUMPKINSPICE"]),
            Puzzle("Thanksgiving Feast", ["TURKEY", "MASHED", "STUFFING", "GRAVY", "CRANBERRY", "ROLLS", "CASSEROLE", "PUMPKINPIE", "YAMS", "CORN", "BUTTER", "FEAST"]),
            Puzzle("Apple Orchard", ["APPLE", "PICKING", "ORCHARD", "CIDER", "BUSHEL", "CRISP", "TREE", "LADDER", "BASKET", "CARAMEL", "HARVEST", "RED"]),
            Puzzle("Grateful Heart", ["GRATITUDE", "THANKFUL", "FAMILY", "BLESSING", "TOGETHER", "WARMTH", "KINDNESS", "SHARING", "LOVE", "GIVING", "HOME", "JOY"]),
            Puzzle("Autumn Walk", ["TRAIL", "LEAVES", "CRISP", "BREEZE", "BOOTS", "ACORN", "SQUIRREL", "FOREST", "PATH", "SWEATER", "CHILLY", "GOLDEN"]),
        ],
    },
    {
        "slug": "wine-lovers-word-search",
        "title": "Wine Lover's Word Search",
        "subtitle": "Puzzles to sip and solve",
        "color": (54, 18, 28),
        "puzzles": [
            Puzzle("Wine Types", ["MERLOT", "CABERNET", "CHARDONNAY", "PINOT", "RIESLING", "ZINFANDEL", "MALBEC", "SHIRAZ", "ROSE", "PROSECCO", "SAUVIGNON", "CHIANTI"]),
            Puzzle("Tasting Notes", ["AROMA", "OAK", "TANNIN", "FRUITY", "BOUQUET", "FINISH", "BODY", "CRISP", "VELVET", "SPICY", "EARTHY", "SMOOTH"]),
            Puzzle("In The Vineyard", ["GRAPES", "VINE", "HARVEST", "TRELLIS", "CELLAR", "BARREL", "TERROIR", "VINTAGE", "ESTATE", "ROWS", "SOIL", "SUN"]),
            Puzzle("Wine Bar", ["GLASS", "DECANTER", "CORK", "BOTTLE", "POUR", "SWIRL", "SIP", "PAIRING", "CHEERS", "CARAFE", "STEM", "TASTING"]),
            Puzzle("Wine Regions", ["TUSCANY", "BORDEAUX", "NAPA", "RIOJA", "PROVENCE", "MOSEL", "CHIANTI", "BURGUNDY", "DOURO", "BAROLO", "ALSACE", "VENETO"]),
            Puzzle("Red Or White", ["MERLOT", "CHARDONNAY", "ROSE", "PINOT", "RIESLING", "CABERNET", "BLANC", "NOIR", "BLEND", "SPARKLING", "SWEET", "DRY"]),
            Puzzle("Cheese Pairings", ["BRIE", "GOUDA", "CHEDDAR", "PARMESAN", "BLUE", "CAMEMBERT", "MANCHEGO", "GRAPES", "CRACKERS", "HONEY", "WALNUTS", "FIG"]),
            Puzzle("Wine Time", ["RELAX", "UNWIND", "EVENING", "FRIENDS", "CHEERS", "POUR", "SAVOR", "COZY", "FIREPLACE", "TOAST", "CANDLE", "GLASS"]),
            Puzzle("Bubbly", ["PROSECCO", "CHAMPAGNE", "SPARKLING", "BUBBLES", "TOAST", "CELEBRATE", "FIZZ", "CHEERS", "FLUTE", "CORK", "POP", "BRUT"]),
            Puzzle("Wine Words", ["VINTAGE", "BOUQUET", "CELLAR", "SOMMELIER", "DECANT", "RESERVE", "BLEND", "AROMA", "LABEL", "CORKED", "SWIRL", "OAK"]),
        ],
    },
    {
        "slug": "tea-lovers-word-search",
        "title": "Tea Lover's Word Search",
        "subtitle": "Steep, sip, and solve",
        "color": (40, 54, 40),
        "puzzles": [
            Puzzle("Tea Types", ["GREEN", "BLACK", "OOLONG", "HERBAL", "CHAMOMILE", "EARLGREY", "MATCHA", "ROOIBOS", "WHITE", "CHAI", "JASMINE", "MINT"]),
            Puzzle("Tea Time", ["TEAPOT", "KETTLE", "STEEP", "BREW", "CUP", "SAUCER", "INFUSER", "STRAINER", "POUR", "SIP", "WARM", "COZY"]),
            Puzzle("Herbal Teas", ["CHAMOMILE", "PEPPERMINT", "GINGER", "HIBISCUS", "LAVENDER", "LEMONGRASS", "ROOIBOS", "NETTLE", "FENNEL", "SAGE", "ECHINACEA", "THYME"]),
            Puzzle("Tea Ceremony", ["MATCHA", "WHISK", "BOWL", "BAMBOO", "RITUAL", "POWDER", "FROTH", "HARMONY", "RESPECT", "CALM", "TRADITION", "SILENCE"]),
            Puzzle("Tea Flavors", ["VANILLA", "HONEY", "LEMON", "GINGER", "MINT", "CINNAMON", "BERGAMOT", "JASMINE", "PEACH", "SPICE", "CARAMEL", "ROSE"]),
            Puzzle("Afternoon Tea", ["SCONES", "CLOTTEDCREAM", "JAM", "SANDWICH", "PASTRY", "CAKE", "TEAPOT", "DOILY", "CHINA", "ELEGANT", "TIERS", "TREATS"]),
            Puzzle("Tea Garden", ["LEAVES", "BUSH", "HARVEST", "HILLS", "MIST", "PLUCKING", "TERRACE", "GREEN", "ESTATE", "SHADE", "PLANTATION", "DEW"]),
            Puzzle("Cozy Brew", ["BLANKET", "BOOK", "FIREPLACE", "STEAM", "WARM", "RAINY", "QUIET", "MUG", "HONEY", "SLOW", "COMFORT", "RELAX"]),
            Puzzle("Tea Around World", ["CHAI", "MATCHA", "OOLONG", "MASALA", "MOROCCAN", "ENGLISH", "RUSSIAN", "TIBETAN", "THAI", "TURKISH", "JAPANESE", "INDIAN"]),
            Puzzle("Tea Words", ["STEEP", "INFUSE", "BREW", "LOOSE", "LEAF", "BLEND", "AROMA", "WARMTH", "CUPPA", "KETTLE", "SOOTHE", "SIP"]),
        ],
    },
    {
        "slug": "travel-word-search",
        "title": "Travel & Wanderlust Word Search",
        "subtitle": "Puzzles for people with itchy feet",
        "color": (28, 52, 66),
        "puzzles": [
            Puzzle("Travel Words", ["PASSPORT", "SUITCASE", "JOURNEY", "ADVENTURE", "EXPLORE", "MAP", "TICKET", "WANDER", "VOYAGE", "DESTINATION", "LUGGAGE", "COMPASS"]),
            Puzzle("Pack Your Bags", ["SUITCASE", "PASSPORT", "CHARGER", "CAMERA", "TOILETRIES", "MAP", "SNACKS", "HEADPHONES", "TICKETS", "ADAPTER", "CLOTHES", "SHOES"]),
            Puzzle("At The Airport", ["BOARDING", "GATE", "TERMINAL", "LUGGAGE", "SECURITY", "PASSPORT", "DEPARTURE", "ARRIVAL", "RUNWAY", "LOUNGE", "CHECKIN", "VISA"]),
            Puzzle("World Wonders", ["COLOSSEUM", "PYRAMID", "TAJMAHAL", "GREATWALL", "EIFFEL", "PETRA", "MACHUPICCHU", "ACROPOLIS", "STONEHENGE", "LOUVRE", "SAGRADA", "BIGBEN"]),
            Puzzle("Beach Getaway", ["SUNSCREEN", "HAMMOCK", "PALM", "SNORKEL", "RESORT", "WAVES", "COCKTAIL", "SANDALS", "SUNSET", "LAGOON", "TROPICAL", "RELAX"]),
            Puzzle("City Break", ["MUSEUM", "CAFE", "SUBWAY", "SKYLINE", "MARKET", "HOTEL", "GALLERY", "PLAZA", "NIGHTLIFE", "LANDMARK", "STROLL", "TOUR"]),
            Puzzle("Road Trip", ["HIGHWAY", "PLAYLIST", "SNACKS", "MAP", "DINER", "MOTEL", "SCENERY", "DETOUR", "GASOLINE", "SUNROOF", "MILES", "ADVENTURE"]),
            Puzzle("Adventure", ["HIKING", "SAFARI", "DIVING", "CLIMBING", "KAYAK", "ZIPLINE", "TREK", "CAMPING", "RAFTING", "EXPLORE", "SUMMIT", "TRAIL"]),
            Puzzle("Souvenirs", ["MAGNET", "POSTCARD", "KEYCHAIN", "SNOWGLOBE", "TRINKET", "CRAFT", "POTTERY", "SCARF", "STAMP", "SHELL", "HANDMADE", "GIFT"]),
            Puzzle("Wanderlust", ["EXPLORE", "DREAM", "HORIZON", "FREEDOM", "DISCOVER", "JOURNEY", "ROAM", "ESCAPE", "NOMAD", "MAP", "COMPASS", "BUCKETLIST"]),
        ],
    },
    {
        "slug": "music-lovers-word-search",
        "title": "Music Lover's Word Search",
        "subtitle": "Puzzles for people who live for music",
        "color": (44, 32, 60),
        "puzzles": [
            Puzzle("Instruments", ["GUITAR", "PIANO", "VIOLIN", "DRUMS", "TRUMPET", "FLUTE", "CELLO", "SAXOPHONE", "HARP", "CLARINET", "BANJO", "UKULELE"]),
            Puzzle("Music Genres", ["JAZZ", "BLUES", "ROCK", "CLASSICAL", "REGGAE", "FOLK", "COUNTRY", "SOUL", "FUNK", "METAL", "INDIE", "DISCO"]),
            Puzzle("Music Theory", ["MELODY", "HARMONY", "RHYTHM", "TEMPO", "CHORD", "SCALE", "OCTAVE", "PITCH", "BEAT", "NOTE", "REST", "KEY"]),
            Puzzle("Orchestra", ["CONDUCTOR", "STRINGS", "BRASS", "WOODWIND", "PERCUSSION", "SCORE", "BATON", "ENSEMBLE", "SOLOIST", "TUNING", "SECTION", "STAGE"]),
            Puzzle("In The Studio", ["MICROPHONE", "MIXER", "TRACK", "RECORD", "PLAYBACK", "STUDIO", "HEADPHONES", "AMPLIFIER", "SESSION", "VOCALS", "LOOP", "MASTER"]),
            Puzzle("Singing", ["VOCALIST", "CHOIR", "SOPRANO", "ALTO", "TENOR", "LYRICS", "CHORUS", "VERSE", "FALSETTO", "ANTHEM", "BALLAD", "DUET"]),
            Puzzle("Concert Night", ["CROWD", "ENCORE", "SPOTLIGHT", "TICKET", "BACKSTAGE", "SETLIST", "SPEAKER", "APPLAUSE", "FESTIVAL", "ROADIE", "LIGHTS", "STAGE"]),
            Puzzle("Piano Keys", ["IVORY", "PEDAL", "SHARP", "FLAT", "MAJOR", "MINOR", "KEYBOARD", "BENCH", "SUSTAIN", "TREBLE", "BASS", "OCTAVE"]),
            Puzzle("Guitar Gear", ["STRINGS", "FRET", "PICK", "CAPO", "TUNER", "STRAP", "BRIDGE", "NECK", "PEDAL", "STRUM", "CHORD", "AMPLIFIER"]),
            Puzzle("Music Words", ["TUNE", "SOUND", "BAND", "ALBUM", "SINGLE", "REMIX", "GROOVE", "JAM", "MELODY", "SOLO", "RECORD", "SONG"]),
        ],
    },
    {
        "slug": "cooking-baking-word-search",
        "title": "Kitchen & Baking Word Search",
        "subtitle": "Tasty puzzles for home cooks and bakers",
        "color": (68, 36, 28),
        "puzzles": [
            Puzzle("In The Kitchen", ["OVEN", "STOVE", "WHISK", "SPATULA", "LADLE", "COLANDER", "SKILLET", "BLENDER", "GRATER", "TIMER", "APRON", "KNIFE"]),
            Puzzle("Baking Basics", ["FLOUR", "SUGAR", "BUTTER", "EGGS", "YEAST", "VANILLA", "BAKINGSODA", "SALT", "MILK", "CREAM", "COCOA", "HONEY"]),
            Puzzle("Sweet Treats", ["COOKIE", "BROWNIE", "MUFFIN", "CUPCAKE", "PIE", "TART", "SCONE", "PUDDING", "CHEESECAKE", "DONUT", "ECLAIR", "FUDGE"]),
            Puzzle("Cooking Methods", ["ROAST", "GRILL", "SAUTE", "SIMMER", "BOIL", "STEAM", "BRAISE", "FRY", "POACH", "BAKE", "BROIL", "BLANCH"]),
            Puzzle("Herbs And Spices", ["BASIL", "OREGANO", "THYME", "ROSEMARY", "PAPRIKA", "CUMIN", "GINGER", "NUTMEG", "CILANTRO", "PARSLEY", "SAGE", "PEPPER"]),
            Puzzle("Pasta Night", ["SPAGHETTI", "PENNE", "LASAGNA", "RAVIOLI", "FETTUCCINE", "MARINARA", "PESTO", "RIGATONI", "GNOCCHI", "ALFREDO", "NOODLE", "SAUCE"]),
            Puzzle("Breakfast", ["PANCAKE", "WAFFLE", "OMELETTE", "BACON", "TOAST", "CEREAL", "GRANOLA", "OATMEAL", "MUFFIN", "BAGEL", "SYRUP", "JAM"]),
            Puzzle("Kitchen Tools", ["ROLLINGPIN", "MIXER", "SIEVE", "TONGS", "PEELER", "MEASURING", "SPATULA", "WHISK", "CUTTER", "BRUSH", "BOWL", "SCALE"]),
            Puzzle("Flavors", ["SWEET", "SAVORY", "SPICY", "TANGY", "SMOKY", "BUTTERY", "ZESTY", "RICH", "CREAMY", "CARAMEL", "CITRUS", "UMAMI"]),
            Puzzle("Bake Sale", ["FROSTING", "SPRINKLES", "BATTER", "DOUGH", "ICING", "GLAZE", "RECIPE", "PREHEAT", "KNEAD", "RISE", "COOL", "SLICE"]),
        ],
    },
    {
        "slug": "ocean-sea-word-search",
        "title": "Ocean & Sea Life Word Search",
        "subtitle": "Puzzles to dive into for sea lovers",
        "color": (16, 46, 62),
        "puzzles": [
            Puzzle("Sea Creatures", ["DOLPHIN", "WHALE", "OCTOPUS", "JELLYFISH", "SEAHORSE", "STARFISH", "TURTLE", "SHARK", "STINGRAY", "CRAB", "LOBSTER", "CLAM"]),
            Puzzle("Coral Reef", ["CORAL", "ANEMONE", "CLOWNFISH", "SPONGE", "REEF", "ALGAE", "LAGOON", "POLYP", "SEAGRASS", "EELGRASS", "PARROTFISH", "ANGELFISH"]),
            Puzzle("On The Shore", ["SEASHELL", "SAND", "TIDE", "DRIFTWOOD", "PEBBLE", "FOAM", "SEAWEED", "DUNE", "ROCKPOOL", "WAVE", "SHORELINE", "GULL"]),
            Puzzle("Whales And Dolphins", ["HUMPBACK", "ORCA", "BELUGA", "NARWHAL", "BLUEWHALE", "PORPOISE", "BLOWHOLE", "FLUKE", "MIGRATE", "POD", "BREACH", "SONAR"]),
            Puzzle("Under The Sea", ["KELP", "CURRENT", "DEPTH", "ABYSS", "TRENCH", "PLANKTON", "SEABED", "MARINE", "FATHOM", "RIPTIDE", "SUBMERGE", "DRIFT"]),
            Puzzle("Ocean Words", ["WAVE", "TIDE", "SALT", "BLUE", "DEEP", "VAST", "HORIZON", "SPLASH", "FOAM", "SURF", "BREEZE", "SWELL"]),
            Puzzle("Beach Day", ["SUNSCREEN", "BUCKET", "SANDCASTLE", "SNORKEL", "TOWEL", "SEAGULL", "FLIPFLOP", "PARASOL", "SWIMSUIT", "COOLER", "SHELL", "WAVES"]),
            Puzzle("Fish", ["SALMON", "TUNA", "COD", "MACKEREL", "SARDINE", "ANCHOVY", "SNAPPER", "HERRING", "GROUPER", "MARLIN", "SWORDFISH", "GUPPY"]),
            Puzzle("Sailing", ["ANCHOR", "COMPASS", "MAST", "SAIL", "HARBOR", "VOYAGE", "CAPTAIN", "RUDDER", "DECK", "KNOT", "PORT", "HORIZON"]),
            Puzzle("Tide Pool", ["STARFISH", "ANEMONE", "BARNACLE", "HERMIT", "URCHIN", "MUSSEL", "LIMPET", "SNAIL", "KELP", "PEBBLE", "SHRIMP", "ROCKPOOL"]),
        ],
    },
    {
        "slug": "birds-word-search",
        "title": "Birds & Birdwatching Word Search",
        "subtitle": "Puzzles for birdwatchers and bird lovers",
        "color": (28, 52, 40),
        "puzzles": [
            Puzzle("Garden Birds", ["ROBIN", "SPARROW", "FINCH", "WREN", "BLUEJAY", "CARDINAL", "CHICKADEE", "STARLING", "NUTHATCH", "WARBLER", "THRUSH", "TITMOUSE"]),
            Puzzle("Birds Of Prey", ["EAGLE", "HAWK", "FALCON", "OWL", "OSPREY", "KESTREL", "VULTURE", "HARRIER", "BUZZARD", "CONDOR", "KITE", "MERLIN"]),
            Puzzle("Water Birds", ["DUCK", "SWAN", "GOOSE", "HERON", "PELICAN", "FLAMINGO", "KINGFISHER", "MALLARD", "EGRET", "LOON", "GREBE", "CRANE"]),
            Puzzle("Birdwatching", ["BINOCULARS", "FEEDER", "NEST", "FIELDGUIDE", "MIGRATION", "HABITAT", "PERCH", "FLOCK", "PLUMAGE", "BIRDBATH", "SPECIES", "SPOTTING"]),
            Puzzle("Songbirds", ["NIGHTINGALE", "LARK", "CANARY", "MOCKINGBIRD", "ORIOLE", "BLACKBIRD", "BUNTING", "SISKIN", "REDWING", "LINNET", "TANAGER", "SONG"]),
            Puzzle("Tropical Birds", ["PARROT", "TOUCAN", "MACAW", "COCKATOO", "PARAKEET", "LORIKEET", "HORNBILL", "QUETZAL", "SUNBIRD", "WEAVER", "COCKATIEL", "FINCH"]),
            Puzzle("Bird Anatomy", ["FEATHER", "BEAK", "TALON", "WING", "CREST", "PLUMAGE", "TAIL", "GIZZARD", "CLAW", "DOWN", "QUILL", "BREAST"]),
            Puzzle("Backyard Feeder", ["SEED", "SUET", "NECTAR", "MILLET", "PEANUT", "FEEDER", "BIRDBATH", "PERCH", "SUNFLOWER", "MEALWORM", "NIGER", "FRUIT"]),
            Puzzle("Owls", ["BARN", "SNOWY", "TAWNY", "SCREECH", "HORNED", "HOOT", "NOCTURNAL", "TALONS", "SILENT", "FEATHER", "PELLET", "ROOST"]),
            Puzzle("Bird Words", ["FLIGHT", "CHIRP", "TWEET", "NEST", "FLOCK", "SOAR", "MIGRATE", "FEATHER", "WINGSPAN", "PERCH", "GLIDE", "AVIARY"]),
        ],
    },
    {
        "slug": "camping-word-search",
        "title": "Camping & Outdoors Word Search",
        "subtitle": "Puzzles for campers and the great outdoors",
        "color": (38, 48, 30),
        "puzzles": [
            Puzzle("Campsite", ["TENT", "CAMPFIRE", "SLEEPINGBAG", "LANTERN", "BACKPACK", "COMPASS", "FLASHLIGHT", "COOLER", "HAMMOCK", "FIREWOOD", "MARSHMALLOW", "MAP"]),
            Puzzle("In The Wild", ["FOREST", "TRAIL", "RIVER", "MOUNTAIN", "MEADOW", "VALLEY", "WILDLIFE", "CANYON", "RIDGE", "STREAM", "WOODS", "SUMMIT"]),
            Puzzle("Camp Cooking", ["SKEWER", "GRILL", "KETTLE", "CAMPSTOVE", "FOIL", "SKILLET", "ROASTING", "COOLER", "CANTEEN", "MESSKIT", "EMBERS", "COCOA"]),
            Puzzle("Hiking Gear", ["BOOTS", "BACKPACK", "TREKPOLE", "CANTEEN", "MAP", "COMPASS", "RAINCOAT", "SOCKS", "HEADLAMP", "WHISTLE", "GAITERS", "BLISTER"]),
            Puzzle("Around The Fire", ["FLAMES", "EMBERS", "SMOKE", "KINDLING", "FIREWOOD", "SPARKS", "STORIES", "SMORES", "GUITAR", "BLANKET", "WARMTH", "CRACKLE"]),
            Puzzle("Wildlife", ["DEER", "BEAR", "FOX", "RACCOON", "SQUIRREL", "OWL", "RABBIT", "MOOSE", "BEAVER", "CHIPMUNK", "COYOTE", "ELK"]),
            Puzzle("Outdoor Activities", ["HIKING", "FISHING", "KAYAKING", "CLIMBING", "CANOEING", "FORAGING", "BIRDING", "RAFTING", "CYCLING", "STARGAZING", "SWIMMING", "TREKKING"]),
            Puzzle("Night Sky", ["STARS", "MOON", "CONSTELLATION", "GALAXY", "METEOR", "ORION", "MILKYWAY", "PLANET", "COMET", "TWINKLE", "COSMOS", "NIGHT"]),
            Puzzle("Camp Skills", ["KNOT", "SHELTER", "NAVIGATE", "FIRESTART", "FORAGE", "PURIFY", "PITCH", "MAPREAD", "SIGNAL", "FIRSTAID", "TRACKING", "SURVIVE"]),
            Puzzle("Nature Words", ["SUNRISE", "BREEZE", "PEACEFUL", "RUGGED", "WILDERNESS", "FRESHAIR", "SCENIC", "REMOTE", "EXPLORE", "TRANQUIL", "ROAM", "VISTA"]),
        ],
    },
    {
        "slug": "yoga-mindfulness-word-search",
        "title": "Yoga & Mindfulness Word Search",
        "subtitle": "Calming puzzles for a mindful moment",
        "color": (50, 40, 58),
        "puzzles": [
            Puzzle("Yoga Poses", ["WARRIOR", "DOWNWARDDOG", "TREE", "COBRA", "CHILD", "LOTUS", "PLANK", "BRIDGE", "TRIANGLE", "MOUNTAIN", "PIGEON", "CAMEL"]),
            Puzzle("Mindfulness", ["BREATH", "PRESENT", "AWARENESS", "STILLNESS", "CALM", "FOCUS", "CLARITY", "GRATITUDE", "ACCEPTANCE", "NOTICE", "PAUSE", "SERENITY"]),
            Puzzle("Meditation", ["MANTRA", "SILENCE", "CHAKRA", "INCENSE", "CUSHION", "POSTURE", "INHALE", "EXHALE", "CENTER", "GROUND", "RELEASE", "OBSERVE"]),
            Puzzle("Breathwork", ["INHALE", "EXHALE", "DEEP", "RHYTHM", "BELLY", "NOSTRIL", "PRANA", "FLOW", "STEADY", "CALM", "RELEASE", "OXYGEN"]),
            Puzzle("Yoga Studio", ["MAT", "BLOCK", "STRAP", "BOLSTER", "BLANKET", "INCENSE", "CANDLE", "MIRROR", "BAREFOOT", "QUIET", "FLOW", "CLASS"]),
            Puzzle("Calm Words", ["PEACE", "SERENE", "TRANQUIL", "GENTLE", "SOFTEN", "EASE", "HARMONY", "BALANCE", "QUIET", "SOOTHE", "RELAX", "STILL"]),
            Puzzle("The Body", ["SPINE", "SHOULDERS", "HIPS", "CORE", "BREATH", "MUSCLE", "POSTURE", "BALANCE", "FLEXIBLE", "STRETCH", "ALIGN", "STRENGTH"]),
            Puzzle("Wellness", ["SELFCARE", "REST", "NOURISH", "HYDRATE", "JOURNAL", "NATURE", "SLEEP", "BALANCE", "HEALING", "RENEW", "RETREAT", "GLOW"]),
            Puzzle("Yoga Styles", ["HATHA", "VINYASA", "ASHTANGA", "YIN", "RESTORATIVE", "KUNDALINI", "POWER", "FLOW", "GENTLE", "BIKRAM", "IYENGAR", "NIDRA"]),
            Puzzle("Inner Peace", ["GRATITUDE", "INTENTION", "KINDNESS", "PATIENCE", "COMPASSION", "PRESENCE", "BREATHE", "RELEASE", "ACCEPT", "REFLECT", "SOOTHE", "CALM"]),
        ],
    },
    {
        "slug": "sports-word-search",
        "title": "Sports & Games Word Search",
        "subtitle": "Puzzles for sports fans and players",
        "color": (26, 42, 58),
        "puzzles": [
            Puzzle("Team Sports", ["FOOTBALL", "BASKETBALL", "BASEBALL", "SOCCER", "HOCKEY", "VOLLEYBALL", "RUGBY", "CRICKET", "LACROSSE", "HANDBALL", "WATERPOLO", "NETBALL"]),
            Puzzle("Olympic Sports", ["SWIMMING", "GYMNASTICS", "ATHLETICS", "DIVING", "ROWING", "FENCING", "ARCHERY", "CYCLING", "JUDO", "BOXING", "SAILING", "HURDLES"]),
            Puzzle("On The Field", ["GOAL", "REFEREE", "WHISTLE", "JERSEY", "STADIUM", "COACH", "KICKOFF", "PENALTY", "OFFSIDE", "TACKLE", "HALFTIME", "SCOREBOARD"]),
            Puzzle("Racket Sports", ["TENNIS", "BADMINTON", "SQUASH", "PINGPONG", "RACKET", "SERVE", "VOLLEY", "BASELINE", "NET", "RALLY", "SMASH", "COURT"]),
            Puzzle("Track And Field", ["SPRINT", "MARATHON", "RELAY", "JAVELIN", "DISCUS", "LONGJUMP", "HIGHJUMP", "HURDLE", "SHOTPUT", "POLEVAULT", "RUNNER", "FINISH"]),
            Puzzle("Winter Sports", ["SKIING", "SNOWBOARD", "SKATING", "HOCKEY", "CURLING", "BOBSLED", "LUGE", "SLALOM", "MOGULS", "BIATHLON", "SLEDDING", "ICE"]),
            Puzzle("Gym Day", ["TREADMILL", "WEIGHTS", "DUMBBELL", "SQUAT", "LUNGE", "CARDIO", "STRETCH", "PLANK", "ROWING", "PUSHUP", "TRAINER", "SWEAT"]),
            Puzzle("Ball Games", ["DRIBBLE", "PASS", "SHOOT", "CATCH", "THROW", "BOUNCE", "SCORE", "DUNK", "HEADER", "VOLLEY", "PITCH", "PUNT"]),
            Puzzle("Game Night", ["CHESS", "CHECKERS", "DOMINOES", "DARTS", "BILLIARDS", "BOWLING", "CARDS", "DICE", "PUZZLE", "TRIVIA", "SCRABBLE", "JENGA"]),
            Puzzle("Sports Words", ["VICTORY", "CHAMPION", "TROPHY", "MEDAL", "TEAMWORK", "PRACTICE", "RECORD", "RIVAL", "FANS", "ARENA", "LEAGUE", "PLAYOFF"]),
        ],
    },
    {
        "slug": "flowers-word-search",
        "title": "Flowers & Botanical Word Search",
        "subtitle": "Blooming puzzles for flower lovers",
        "color": (72, 34, 48),
        "puzzles": [
            Puzzle("Garden Flowers", ["ROSE", "TULIP", "DAISY", "LILY", "SUNFLOWER", "PEONY", "DAHLIA", "MARIGOLD", "PETUNIA", "ZINNIA", "PANSY", "IRIS"]),
            Puzzle("Wildflowers", ["POPPY", "DANDELION", "BLUEBELL", "FOXGLOVE", "BUTTERCUP", "CLOVER", "THISTLE", "COWSLIP", "HEATHER", "PRIMROSE", "LUPINE", "DAISY"]),
            Puzzle("Flower Parts", ["PETAL", "STEM", "LEAF", "BUD", "POLLEN", "NECTAR", "STAMEN", "ROOT", "THORN", "BLOSSOM", "SEPAL", "PISTIL"]),
            Puzzle("Bouquet", ["ARRANGEMENT", "VASE", "RIBBON", "POSY", "FLORIST", "FRESHCUT", "GREENERY", "BLOOMS", "CORSAGE", "WRAP", "STEMS", "FRAGRANT"]),
            Puzzle("Tropical Flowers", ["HIBISCUS", "ORCHID", "PLUMERIA", "JASMINE", "LOTUS", "PROTEA", "ANTHURIUM", "FRANGIPANI", "LANTANA", "CANNA", "BOUGAINVILLEA", "OLEANDER"]),
            Puzzle("Spring Blooms", ["DAFFODIL", "CROCUS", "HYACINTH", "TULIP", "SNOWDROP", "BLOSSOM", "MAGNOLIA", "LILAC", "WISTERIA", "AZALEA", "CAMELLIA", "FORSYTHIA"]),
            Puzzle("In The Garden", ["TRELLIS", "PLANTER", "SOIL", "WATERING", "SUNLIGHT", "BUMBLEBEE", "BUTTERFLY", "MULCH", "PRUNE", "BLOOM", "FRAGRANCE", "PETALS"]),
            Puzzle("Flower Colors", ["CRIMSON", "LAVENDER", "YELLOW", "CORAL", "BLUSH", "VIOLET", "PEACH", "MAGENTA", "SCARLET", "IVORY", "GOLDEN", "ROSY"]),
            Puzzle("All About Roses", ["PETAL", "THORN", "BUD", "REDROSE", "FRAGRANT", "BOUQUET", "ROMANCE", "VELVET", "CLIMBER", "HYBRID", "BLOOM", "GARDEN"]),
            Puzzle("Botanical Words", ["FLORAL", "BLOOM", "GARDEN", "MEADOW", "FRAGRANT", "DELICATE", "BLOSSOM", "NECTAR", "POLLEN", "GROW", "VINE", "LEAFY"]),
        ],
    },
    {
        "slug": "farm-word-search",
        "title": "Farm & Country Word Search",
        "subtitle": "Puzzles for country and farm lovers",
        "color": (58, 46, 28),
        "puzzles": [
            Puzzle("Farm Animals", ["COW", "PIG", "SHEEP", "CHICKEN", "HORSE", "GOAT", "DUCK", "TURKEY", "ROOSTER", "DONKEY", "RABBIT", "GOOSE"]),
            Puzzle("On The Farm", ["BARN", "TRACTOR", "SILO", "FENCE", "PASTURE", "HAYSTACK", "TROUGH", "STABLE", "COOP", "PADDOCK", "MEADOW", "GATE"]),
            Puzzle("Crops", ["WHEAT", "CORN", "BARLEY", "OATS", "SOYBEAN", "POTATO", "PUMPKIN", "TOMATO", "LETTUCE", "CARROT", "CABBAGE", "ORCHARD"]),
            Puzzle("Farm Tools", ["PLOW", "SHOVEL", "PITCHFORK", "RAKE", "WHEELBARROW", "HOE", "HARVESTER", "BUCKET", "TROWEL", "SCYTHE", "SHEARS", "HAMMER"]),
            Puzzle("Baby Animals", ["CALF", "PIGLET", "LAMB", "CHICK", "FOAL", "KID", "DUCKLING", "GOSLING", "BUNNY", "KITTEN", "PUPPY", "POULT"]),
            Puzzle("Country Life", ["MEADOW", "ORCHARD", "COTTAGE", "HAYRIDE", "HARVEST", "GARDEN", "WELL", "CREEK", "WINDMILL", "ROOSTER", "SUNRISE", "PORCH"]),
            Puzzle("Dairy", ["MILK", "CHEESE", "BUTTER", "CREAM", "YOGURT", "CHURN", "PAIL", "UDDER", "CURDS", "DAIRY", "WHEY", "CALCIUM"]),
            Puzzle("Harvest Time", ["WHEAT", "BUSHEL", "SCARECROW", "GRANARY", "THRESH", "BALE", "HAYLOFT", "PLENTY", "AUTUMN", "CROP", "GATHER", "YIELD"]),
            Puzzle("Farm Sounds", ["MOO", "OINK", "CLUCK", "NEIGH", "BAA", "QUACK", "GOBBLE", "BRAY", "CROW", "BLEAT", "HONK", "WHINNY"]),
            Puzzle("Country Words", ["RUSTIC", "PEACEFUL", "PASTORAL", "SIMPLE", "HOMESTEAD", "ACRES", "RURAL", "COUNTRY", "HARVEST", "WHOLESOME", "EARTHY", "HEARTH"]),
        ],
    },
    {
        "slug": "space-word-search",
        "title": "Space & Astronomy Word Search",
        "subtitle": "Out-of-this-world puzzles for stargazers",
        "color": (18, 22, 44),
        "puzzles": [
            Puzzle("Planets", ["MERCURY", "VENUS", "EARTH", "MARS", "JUPITER", "SATURN", "URANUS", "NEPTUNE", "PLUTO", "PLANET", "ORBIT", "MOON"]),
            Puzzle("The Night Sky", ["STARS", "MOON", "GALAXY", "NEBULA", "COMET", "METEOR", "CONSTELLATION", "MILKYWAY", "ECLIPSE", "AURORA", "TWINKLE", "COSMOS"]),
            Puzzle("Space Travel", ["ROCKET", "ASTRONAUT", "SPACESHIP", "LAUNCH", "ORBIT", "SHUTTLE", "CAPSULE", "SPACESUIT", "LIFTOFF", "GRAVITY", "DOCKING", "MISSION"]),
            Puzzle("Solar System", ["SUN", "ASTEROID", "COMET", "MOONS", "RINGS", "ORBIT", "GRAVITY", "SOLAR", "CRATER", "ECLIPSE", "ROTATION", "SATELLITE"]),
            Puzzle("Constellations", ["ORION", "URSAMAJOR", "CASSIOPEIA", "LEO", "GEMINI", "SCORPIUS", "TAURUS", "DRACO", "PEGASUS", "LYRA", "AQUARIUS", "ANDROMEDA"]),
            Puzzle("Astronomy Tools", ["TELESCOPE", "OBSERVATORY", "LENS", "TRIPOD", "STARCHART", "BINOCULARS", "DOME", "MAGNIFY", "SPECTRUM", "MIRROR", "EYEPIECE", "FILTER"]),
            Puzzle("Deep Space", ["GALAXY", "NEBULA", "BLACKHOLE", "SUPERNOVA", "QUASAR", "PULSAR", "LIGHTYEAR", "COSMOS", "VOID", "INFINITE", "STARDUST", "VASTNESS"]),
            Puzzle("Space Words", ["EXPLORE", "DISCOVERY", "MISSION", "ORBIT", "COSMIC", "STELLAR", "LUNAR", "CELESTIAL", "INTERSTELLAR", "VOYAGE", "WONDER", "INFINITY"]),
            Puzzle("The Moon", ["CRATER", "PHASE", "FULLMOON", "CRESCENT", "LUNAR", "TIDES", "ECLIPSE", "HALFMOON", "SURFACE", "GLOW", "ORBIT", "HALO"]),
            Puzzle("Astronauts", ["SPACESUIT", "HELMET", "MISSION", "SHUTTLE", "WEIGHTLESS", "TRAINING", "CREW", "MODULE", "SPACEWALK", "OXYGEN", "VISOR", "EXPLORE"]),
        ],
    },
    {
        "slug": "fishing-word-search",
        "title": "Fishing Word Search",
        "subtitle": "Puzzles for anglers and fishing fans",
        "color": (20, 50, 58),
        "puzzles": [
            Puzzle("Fishing Gear", ["ROD", "REEL", "HOOK", "BAIT", "LINE", "TACKLE", "LURE", "SINKER", "BOBBER", "NET", "FLOAT", "SWIVEL"]),
            Puzzle("Freshwater Fish", ["BASS", "TROUT", "CATFISH", "PERCH", "PIKE", "CARP", "WALLEYE", "CRAPPIE", "BLUEGILL", "SALMON", "SUNFISH", "MUSKIE"]),
            Puzzle("Saltwater Fish", ["TUNA", "MARLIN", "SNAPPER", "GROUPER", "MACKEREL", "FLOUNDER", "HALIBUT", "TARPON", "SEABASS", "SWORDFISH", "MAHIMAHI", "COD"]),
            Puzzle("On The Water", ["BOAT", "LAKE", "RIVER", "DOCK", "PIER", "CAST", "ANCHOR", "CURRENT", "RIPPLE", "SHORE", "DEPTH", "PADDLE"]),
            Puzzle("Fly Fishing", ["FLY", "WADERS", "STREAM", "DRIFT", "RIFFLE", "LEADER", "TIPPET", "NYMPH", "DRYFLY", "CASTING", "MENDING", "TROUT"]),
            Puzzle("Fishing Trip", ["TACKLEBOX", "COOLER", "SUNRISE", "PATIENCE", "CATCH", "RELEASE", "LICENSE", "THERMOS", "HAT", "BUCKET", "WORMS", "QUIET"]),
            Puzzle("Types Of Bait", ["WORM", "MINNOW", "CRICKET", "LEECH", "SHRIMP", "NIGHTCRAWLER", "GRUB", "SPINNER", "JIG", "CRANKBAIT", "MAGGOT", "CORN"]),
            Puzzle("The Catch", ["BITE", "STRIKE", "HOOKSET", "REELIN", "LANDING", "TROPHY", "KEEPER", "LIMIT", "WEIGH", "MEASURE", "PHOTO", "RELEASE"]),
            Puzzle("Fishing Spots", ["LAKE", "POND", "RIVER", "STREAM", "REEF", "HARBOR", "JETTY", "ESTUARY", "CREEK", "INLET", "DEEPSEA", "BANK"]),
            Puzzle("Angler Words", ["PATIENCE", "QUIET", "SUNRISE", "RIPPLE", "TUG", "CATCH", "CALM", "NATURE", "RELAX", "SOLITUDE", "WATERS", "LEGEND"]),
        ],
    },
    {
        "slug": "horses-word-search",
        "title": "Horses & Equestrian Word Search",
        "subtitle": "Puzzles for horse lovers and riders",
        "color": (52, 34, 24),
        "puzzles": [
            Puzzle("Horse Breeds", ["ARABIAN", "MUSTANG", "THOROUGHBRED", "CLYDESDALE", "APPALOOSA", "PALOMINO", "PONY", "MORGAN", "FRIESIAN", "SHIRE", "QUARTER", "PINTO"]),
            Puzzle("Horse Colors", ["BAY", "CHESTNUT", "BLACK", "GREY", "ROAN", "DUN", "PALOMINO", "PINTO", "WHITE", "BUCKSKIN", "PIEBALD", "SORREL"]),
            Puzzle("Riding Gear", ["SADDLE", "BRIDLE", "REINS", "STIRRUP", "HELMET", "HALTER", "GIRTH", "BLANKET", "BOOTS", "WHIP", "BIT", "SPURS"]),
            Puzzle("At The Stable", ["STALL", "BARN", "HAY", "GROOM", "TROUGH", "PADDOCK", "PASTURE", "FARRIER", "MANE", "BRUSH", "FEED", "WATER"]),
            Puzzle("Horse Gaits", ["WALK", "TROT", "CANTER", "GALLOP", "JUMP", "PRANCE", "AMBLE", "PACE", "LOPE", "STRIDE", "HALT", "REARING"]),
            Puzzle("Equestrian Sports", ["DRESSAGE", "JUMPING", "EVENTING", "POLO", "RODEO", "RACING", "VAULTING", "ENDURANCE", "REINING", "HUNTER", "BARREL", "TRAIL"]),
            Puzzle("Horse Anatomy", ["MANE", "HOOF", "TAIL", "WITHERS", "FETLOCK", "MUZZLE", "FLANK", "HOCK", "FORELOCK", "CANNON", "POLL", "CREST"]),
            Puzzle("Horse Care", ["GROOMING", "BRUSHING", "FEEDING", "HOOFPICK", "VETERINARY", "SHOEING", "TURNOUT", "EXERCISE", "BEDDING", "MUCKING", "MANE", "BATH"]),
            Puzzle("Foals", ["FOAL", "COLT", "FILLY", "WEANLING", "YEARLING", "NURSING", "PLAYFUL", "WOBBLY", "DAM", "SIRE", "SPINDLY", "NEWBORN"]),
            Puzzle("Horse Words", ["GALLOP", "FREEDOM", "MAJESTIC", "GRACEFUL", "NOBLE", "SPIRITED", "GENTLE", "LOYAL", "WILD", "ELEGANT", "POWERFUL", "RIDER"]),
        ],
    },
    {
        "slug": "hiking-word-search",
        "title": "Hiking & Mountains Word Search",
        "subtitle": "Puzzles for hikers and mountain lovers",
        "color": (36, 52, 38),
        "puzzles": [
            Puzzle("Hiking Essentials", ["BOOTS", "BACKPACK", "WATER", "MAP", "COMPASS", "SUNSCREEN", "SNACKS", "FIRSTAID", "WHISTLE", "HEADLAMP", "PONCHO", "TREKPOLE"]),
            Puzzle("Mountain Peaks", ["SUMMIT", "RIDGE", "CLIFF", "CREST", "ALPINE", "PEAK", "LEDGE", "PINNACLE", "SADDLE", "BLUFF", "PLATEAU", "OVERLOOK"]),
            Puzzle("On The Trail", ["SWITCHBACK", "BLAZES", "CAIRN", "TRAILHEAD", "FOOTPATH", "SCRAMBLE", "ASCENT", "DESCENT", "LOOP", "RIDGELINE", "PASS", "CREEK"]),
            Puzzle("Mountain Weather", ["SUNRISE", "MIST", "FROST", "THUNDER", "CLOUD", "WIND", "DRIZZLE", "HAIL", "SLEET", "CLEARING", "RAINBOW", "BREEZE"]),
            Puzzle("Wildlife On Trail", ["EAGLE", "DEER", "MARMOT", "GOAT", "BEAR", "RABBIT", "HAWK", "SNAKE", "LIZARD", "CHIPMUNK", "MOOSE", "FOX"]),
            Puzzle("Trail Snacks", ["GRANOLA", "JERKY", "NUTS", "RAISINS", "APPLE", "CHEESE", "CHOCOLATE", "TRAILMIX", "BANANA", "CRACKERS", "PROTEIN", "DRIED"]),
            Puzzle("Mountain Flowers", ["EDELWEISS", "LUPINE", "COLUMBINE", "FIREWEED", "PAINTBRUSH", "GENTIAN", "ASTER", "ARNICA", "SAXIFRAGE", "HEATHER", "YARROW", "ALPINE"]),
            Puzzle("Famous Trails", ["APPALACHIAN", "CAMINO", "KOKODA", "MILFORD", "OVERLAND", "KUNGSLEDEN", "ANNAPURNA", "WICKLOW", "TONGARIRO", "WESTCOAST", "CHILKOOT", "LYCIAN"]),
            Puzzle("Camp At Altitude", ["BIVOUAC", "BASECAMP", "SHELTER", "TARP", "SLEEPING", "TENT", "STOVE", "LAYER", "THERMAL", "ALTITUDE", "SUMMIT", "DAWN"]),
            Puzzle("Hiker Words", ["ADVENTURE", "EXPLORE", "WANDER", "FREEDOM", "SOLITUDE", "BREATHE", "CONQUER", "JOURNEY", "MAJESTIC", "PEACEFUL", "RUGGED", "VISTA"]),
        ],
    },
    {
        "slug": "butterflies-word-search",
        "title": "Butterflies & Insects Word Search",
        "subtitle": "Beautiful puzzles for nature lovers",
        "color": (58, 44, 62),
        "puzzles": [
            Puzzle("Butterflies", ["MONARCH", "SWALLOWTAIL", "PAINTED", "ADMIRAL", "PEACOCK", "MORPHO", "BUCKEYE", "SKIPPER", "VICEROY", "RINGLET", "HAIRSTREAK", "SULPHUR"]),
            Puzzle("Butterfly Life", ["CATERPILLAR", "CHRYSALIS", "COCOON", "LARVAE", "PUPA", "WINGS", "ANTENNA", "NECTAR", "EMERGE", "FLUTTER", "HATCH", "MIGRATE"]),
            Puzzle("Garden Insects", ["LADYBUG", "BEE", "BEETLE", "DRAGONFLY", "CRICKET", "ANT", "GRASSHOPPER", "FIREFLY", "MANTIS", "MOTH", "WASP", "CICADA"]),
            Puzzle("Pollinator Garden", ["NECTAR", "POLLEN", "BUMBLEBEE", "HONEYBEE", "BUTTERFLY", "FLOWER", "BLOOM", "HOVER", "WINGS", "GARDEN", "SUNFLOWER", "LAVENDER"]),
            Puzzle("Moths", ["LUNA", "ATLAS", "SPHINX", "CECROPIA", "HAWK", "SILKWORM", "EMPEROR", "CINNABAR", "TIGER", "GIANT", "NOCTURNAL", "COMET"]),
            Puzzle("Insect Anatomy", ["ANTENNA", "THORAX", "ABDOMEN", "WINGS", "LEGS", "MANDIBLE", "COMPOUND", "SEGMENT", "SPIRACLE", "CHITIN", "LARVA", "SHELL"]),
            Puzzle("Bug Watching", ["MAGNIFIER", "FIELDGUIDE", "HABITAT", "SPECIMEN", "IDENTIFY", "OBSERVE", "SKETCH", "JOURNAL", "COLLECT", "SEASON", "MEADOW", "PATIENT"]),
            Puzzle("Helpful Insects", ["LADYBUG", "BEE", "LACEWING", "HOVERFLY", "EARTHWORM", "SPIDER", "PRAYING", "DRAGONFLY", "BEETLE", "WASP", "POLLINATE", "COMPOST"]),
            Puzzle("Butterfly Garden", ["MILKWEED", "ZINNIA", "ASTER", "CONEFLOWER", "LANTANA", "VERBENA", "BUDDLEIA", "MARIGOLD", "FENNEL", "PARSLEY", "DILL", "CLOVER"]),
            Puzzle("Nature Words", ["DELICATE", "GRACEFUL", "FLUTTER", "SHIMMER", "GOSSAMER", "FRAGILE", "VIBRANT", "ELEGANT", "RADIANT", "COLORFUL", "GENTLE", "DAINTY"]),
        ],
    },
    {
        "slug": "wildlife-word-search",
        "title": "Wildlife & Safari Word Search",
        "subtitle": "Puzzles for animal lovers and adventurers",
        "color": (56, 42, 18),
        "puzzles": [
            Puzzle("African Safari", ["ELEPHANT", "LION", "GIRAFFE", "ZEBRA", "CHEETAH", "HIPPO", "RHINO", "BUFFALO", "LEOPARD", "WILDEBEEST", "GAZELLE", "HYENA"]),
            Puzzle("Forest Animals", ["DEER", "FOX", "BEAR", "WOLF", "RACCOON", "BADGER", "HEDGEHOG", "SQUIRREL", "OWL", "RABBIT", "LYNX", "OTTER"]),
            Puzzle("Big Cats", ["LION", "TIGER", "LEOPARD", "CHEETAH", "JAGUAR", "PANTHER", "COUGAR", "BOBCAT", "LYNX", "OCELOT", "CARACAL", "SERVAL"]),
            Puzzle("Ocean Giants", ["WHALE", "DOLPHIN", "SHARK", "ORCA", "MANTA", "WALRUS", "SEAL", "MANATEE", "NARWHAL", "BELUGA", "DUGONG", "TURTLE"]),
            Puzzle("Rainforest", ["TOUCAN", "JAGUAR", "SLOTH", "MACAW", "GORILLA", "CHAMELEON", "ANACONDA", "MONKEY", "TAPIR", "OKAPI", "LEMUR", "PARROT"]),
            Puzzle("Arctic Animals", ["POLARBEAR", "PENGUIN", "ARCTICFOX", "REINDEER", "WALRUS", "NARWHAL", "LEMMING", "HARE", "PUFFIN", "SEAL", "BELUGA", "ERMINE"]),
            Puzzle("Savanna Life", ["ACACIA", "GRASSLAND", "WATERING", "MIGRATION", "HERDS", "SUNSET", "DUST", "PRIDE", "PACK", "DROUGHT", "BAOBAB", "TERMITE"]),
            Puzzle("Baby Animals", ["CUB", "PUP", "JOEY", "CALF", "KIT", "FAWN", "HATCHLING", "FOAL", "LAMB", "CHICK", "DUCKLING", "FLEDGLING"]),
            Puzzle("Wildlife Words", ["HABITAT", "SPECIES", "PREDATOR", "PREY", "ECOSYSTEM", "MIGRATE", "NOCTURNAL", "CAMOUFLAGE", "TERRITORY", "BURROW", "EXTINCT", "WILD"]),
            Puzzle("Conservation", ["PROTECT", "PRESERVE", "HABITAT", "ENDANGER", "SANCTUARY", "WILDLIFE", "ECOLOGY", "NATURE", "FOREST", "SUSTAIN", "RESCUE", "REWILD"]),
        ],
    },
    {
        "slug": "fitness-word-search",
        "title": "Fitness & Workout Word Search",
        "subtitle": "Pump up your puzzle game",
        "color": (40, 44, 52),
        "puzzles": [
            Puzzle("Gym Equipment", ["DUMBBELL", "BARBELL", "TREADMILL", "KETTLEBELL", "BENCH", "PULLUP", "CABLE", "RACK", "PLATE", "BAND", "ROLLER", "MAT"]),
            Puzzle("Cardio", ["RUNNING", "CYCLING", "SWIMMING", "ROWING", "JUMPING", "HIKING", "DANCING", "BOXING", "SKIPPING", "SPRINTS", "JOGGING", "STAIRS"]),
            Puzzle("Strength Training", ["SQUAT", "DEADLIFT", "PRESS", "CURL", "LUNGE", "PLANK", "PUSHUP", "PULLUP", "ROW", "CRUNCH", "DIP", "SHRUG"]),
            Puzzle("Yoga Poses", ["WARRIOR", "TREE", "COBRA", "LOTUS", "BRIDGE", "PLANK", "CHILD", "EAGLE", "PIGEON", "CAMEL", "CROW", "FISH"]),
            Puzzle("Healthy Eating", ["PROTEIN", "FIBER", "GREENS", "QUINOA", "SALMON", "AVOCADO", "OATS", "CHICKEN", "SPINACH", "BERRIES", "ALMONDS", "WATER"]),
            Puzzle("Running", ["MARATHON", "SPRINT", "TEMPO", "PACE", "STRIDE", "MILE", "TRACK", "TRAIL", "FINISH", "LAPS", "COOLDOWN", "WARMUP"]),
            Puzzle("Fitness Goals", ["STRENGTH", "ENDURANCE", "FLEXIBLE", "BALANCE", "SPEED", "AGILITY", "POWER", "STAMINA", "TONE", "LEAN", "MUSCLE", "CORE"]),
            Puzzle("Workout Classes", ["SPINNING", "PILATES", "CROSSFIT", "ZUMBA", "BARRE", "BOOTCAMP", "KICKBOX", "CIRCUIT", "HIIT", "TABATA", "STRETCH", "FLOW"]),
            Puzzle("Recovery", ["STRETCH", "FOAM", "MASSAGE", "REST", "SLEEP", "HYDRATE", "ICE", "WARMTH", "BREATHE", "RELAX", "SOAK", "HEAL"]),
            Puzzle("Fitness Words", ["REPS", "SETS", "FORM", "GAIN", "BURN", "SWEAT", "GRIND", "BEAST", "PUMP", "FLEX", "PEAK", "DRIVE"]),
        ],
    },
    {
        "slug": "movie-night-word-search",
        "title": "Movie Night Word Search",
        "subtitle": "Lights, camera, puzzles!",
        "color": (30, 30, 48),
        "puzzles": [
            Puzzle("Movie Genres", ["COMEDY", "DRAMA", "HORROR", "ACTION", "ROMANCE", "THRILLER", "WESTERN", "FANTASY", "SCIFI", "MYSTERY", "MUSICAL", "ANIMATED"]),
            Puzzle("At The Cinema", ["POPCORN", "SCREEN", "TICKET", "TRAILER", "SEAT", "AISLE", "PROJECTOR", "SNACK", "CREDITS", "SURROUND", "LOBBY", "SHOWING"]),
            Puzzle("Film Crew", ["DIRECTOR", "PRODUCER", "ACTOR", "WRITER", "EDITOR", "CAMERA", "GRIP", "GAFFER", "COSTUME", "MAKEUP", "SOUND", "STUNT"]),
            Puzzle("Movie Snacks", ["POPCORN", "NACHOS", "CANDY", "SODA", "PRETZEL", "HOTDOG", "GUMMY", "TWIZZLER", "ICECREAM", "CHIPS", "SLURPEE", "BROWNIE"]),
            Puzzle("Classic Movies", ["CASABLANCA", "JAWS", "ROCKY", "GREASE", "GHOSTBUST", "TOPGUN", "MATRIX", "TITANIC", "FORREST", "SHREK", "FROZEN", "WIZARD"]),
            Puzzle("Animation", ["PIXAR", "DISNEY", "GHIBLI", "ANIME", "CARTOON", "SKETCH", "FRAME", "RENDER", "VOICE", "STORYBOARD", "CHARACTER", "SEQUEL"]),
            Puzzle("Movie Night In", ["BLANKET", "COUCH", "REMOTE", "DIMMER", "SNUGGLE", "STREAM", "BINGE", "MARATHON", "PILLOW", "COMFORT", "PAUSE", "REWIND"]),
            Puzzle("Superheroes", ["BATMAN", "SPIDER", "IRON", "CAPTAIN", "WONDER", "FLASH", "HULK", "THOR", "PANTHER", "AQUAMAN", "WOLVERINE", "ROBIN"]),
            Puzzle("Awards", ["OSCAR", "GLOBE", "EMMY", "CANNES", "BAFTA", "SUNDANCE", "PALM", "NOMINEE", "WINNER", "TROPHY", "GALA", "CARPET"]),
            Puzzle("Movie Words", ["SCENE", "PLOT", "TWIST", "CLIMAX", "SEQUEL", "PREQUEL", "CAST", "SCRIPT", "TAKE", "CUT", "WRAP", "DEBUT"]),
        ],
    },
    {
        "slug": "baking-word-search",
        "title": "Baking & Pastry Word Search",
        "subtitle": "Sweet puzzles for bakers",
        "color": (72, 42, 32),
        "puzzles": [
            Puzzle("Bread Baking", ["SOURDOUGH", "BAGUETTE", "BRIOCHE", "FOCACCIA", "CIABATTA", "RYE", "WHEAT", "KNEAD", "PROOF", "CRUST", "CRUMB", "LOAF"]),
            Puzzle("Cake Flavors", ["CHOCOLATE", "VANILLA", "LEMON", "CARROT", "REDVELVET", "COCONUT", "STRAWBERRY", "MARBLE", "FUNFETTI", "BANANA", "COFFEE", "ALMOND"]),
            Puzzle("Pastry Shop", ["CROISSANT", "ECLAIR", "DANISH", "TURNOVER", "STRUDEL", "TART", "PUFFPASTRY", "CANNOLI", "MACARON", "MUFFIN", "SCONE", "DONUT"]),
            Puzzle("Baking Tools", ["WHISK", "SPATULA", "ROLLER", "MIXER", "SIFTER", "PIPING", "MOLD", "SHEET", "RACK", "TIMER", "SCALE", "BOWL"]),
            Puzzle("Cookie Jar", ["CHOCOLATE", "OATMEAL", "SNICKER", "SHORTBREAD", "GINGER", "SUGAR", "PEANUT", "MACADAMIA", "BISCOTTI", "THUMBPRINT", "WAFER", "MERINGUE"]),
            Puzzle("Decorating", ["FROSTING", "FONDANT", "SPRINKLE", "GANACHE", "GLAZE", "ICING", "DRIZZLE", "PIPING", "TOPPER", "RIBBON", "ROSETTE", "LAYER"]),
            Puzzle("Pie Time", ["APPLE", "CHERRY", "PUMPKIN", "PECAN", "BLUEBERRY", "LEMON", "CUSTARD", "LATTICE", "FILLING", "GRAHAM", "MERINGUE", "COBBLER"]),
            Puzzle("Ingredients", ["FLOUR", "SUGAR", "BUTTER", "EGGS", "VANILLA", "YEAST", "CREAM", "COCOA", "SALT", "MILK", "HONEY", "CINNAMON"]),
            Puzzle("Holiday Baking", ["GINGERBREAD", "FRUITCAKE", "STOLLEN", "YULELOG", "PANETTONE", "COOKIES", "FUDGE", "TRUFFLES", "PEPPERMINT", "EGGNOG", "WREATH", "TINSEL"]),
            Puzzle("Baking Words", ["RISE", "FOLD", "CREAM", "WHIP", "BLEND", "BATTER", "DOUGH", "OVEN", "GOLDEN", "COOL", "SLICE", "SERVE"]),
        ],
    },
    {
        "slug": "book-lovers-word-search",
        "title": "Book Lover's Word Search",
        "subtitle": "Puzzles for avid readers",
        "color": (48, 36, 28),
        "puzzles": [
            Puzzle("Book Genres", ["MYSTERY", "ROMANCE", "FANTASY", "THRILLER", "MEMOIR", "POETRY", "SCIFI", "HORROR", "HISTORY", "CLASSIC", "COMEDY", "DRAMA"]),
            Puzzle("At The Library", ["SHELVES", "CATALOG", "CHECKOUT", "READING", "SILENCE", "BOOKMARK", "RETURN", "RESERVE", "FICTION", "SECTION", "STACK", "DESK"]),
            Puzzle("Famous Authors", ["AUSTEN", "DICKENS", "TOLKIEN", "ROWLING", "KING", "TWAIN", "ORWELL", "BRONTE", "HEMINGWAY", "POE", "WILDE", "DUMAS"]),
            Puzzle("Bookstore", ["BROWSE", "DISPLAY", "NEWRELEASE", "BESTSELLER", "CAFE", "SIGNING", "SHELVES", "EDITION", "HARDCOVER", "PAPERBACK", "AISLE", "COZY"]),
            Puzzle("Reading Nook", ["BLANKET", "CUSHION", "LAMP", "WINDOW", "CHAIR", "TEA", "QUIET", "CANDLE", "COZY", "CORNER", "PILLOW", "SNUGGLE"]),
            Puzzle("Book Parts", ["CHAPTER", "PROLOGUE", "EPILOGUE", "INDEX", "COVER", "SPINE", "PAGE", "MARGIN", "BINDING", "TITLE", "PREFACE", "BLURB"]),
            Puzzle("Book Club", ["DISCUSS", "REVIEW", "VOTE", "PICK", "THEME", "MEETING", "OPINION", "DEBATE", "SHARE", "INSIGHT", "REFRESH", "HOST"]),
            Puzzle("Fantasy Worlds", ["DRAGON", "WIZARD", "QUEST", "KINGDOM", "MAGIC", "SWORD", "ELVES", "CASTLE", "PROPHECY", "PORTAL", "ENCHANT", "RUNE"]),
            Puzzle("Mystery Words", ["CLUE", "SUSPECT", "ALIBI", "WITNESS", "MOTIVE", "SLEUTH", "CRIME", "REVEAL", "TWIST", "WHODUNIT", "HIDDEN", "SOLVE"]),
            Puzzle("Reader Words", ["BOOKMARK", "BINGE", "SERIES", "SEQUEL", "SHELF", "STACK", "DEVOUR", "REREAD", "LIBRARY", "FICTION", "NOVEL", "TALE"]),
        ],
    },
    {
        "slug": "teachers-word-search",
        "title": "Teacher's Word Search",
        "subtitle": "Puzzles for educators",
        "color": (38, 50, 56),
        "puzzles": [
            Puzzle("Classroom", ["DESK", "BOARD", "CHALK", "PENCIL", "ERASER", "TEXTBOOK", "GLOBE", "RULER", "BACKPACK", "NOTEBOOK", "MARKER", "CLOCK"]),
            Puzzle("School Subjects", ["MATH", "SCIENCE", "ENGLISH", "HISTORY", "ART", "MUSIC", "READING", "WRITING", "GEOGRAPHY", "BIOLOGY", "PHYSICS", "SPANISH"]),
            Puzzle("Teaching", ["LESSON", "HOMEWORK", "QUIZ", "GRADE", "REPORT", "PARENT", "MEETING", "RECESS", "ASSEMBLY", "FIELD", "PROJECT", "PRESENT"]),
            Puzzle("School Supplies", ["SCISSORS", "GLUE", "CRAYON", "PAPER", "FOLDER", "BINDER", "STAPLER", "TAPE", "STICKER", "STAMP", "HIGHLITE", "SHARPENER"]),
            Puzzle("End Of Year", ["GRADUATE", "DIPLOMA", "CEREMONY", "YEARBOOK", "SUMMER", "VACATION", "MEMORY", "AWARD", "SPEECH", "PHOTO", "PARTY", "FAREWELL"]),
            Puzzle("School Life", ["CAFETERIA", "HALLWAY", "LOCKER", "GYM", "LIBRARY", "OFFICE", "NURSE", "BELL", "BUS", "PLAYGROUND", "COURTYARD", "ENTRANCE"]),
            Puzzle("Teacher Gifts", ["APPLE", "COFFEE", "MUG", "CANDLE", "FLOWERS", "BOOKMARK", "PLANNER", "PEN", "TOTE", "CHOCOLATE", "CARD", "GRATEFUL"]),
            Puzzle("Learning", ["STUDY", "PRACTICE", "FOCUS", "REVIEW", "EXPLORE", "DISCOVER", "QUESTION", "RESEARCH", "SKILL", "GROW", "IMPROVE", "ACHIEVE"]),
            Puzzle("Back To School", ["SUPPLIES", "SCHEDULE", "UNIFORM", "LUNCHBOX", "CARPOOL", "TEACHER", "FRIENDS", "HOMEROOM", "SYLLABUS", "LOCKER", "PLANNER", "PENCIL"]),
            Puzzle("Teacher Words", ["INSPIRE", "MENTOR", "GUIDE", "PATIENCE", "DEDICATE", "EDUCATE", "NURTURE", "EMPOWER", "SUPPORT", "MOTIVATE", "SHAPE", "LEAD"]),
        ],
    },
    {
        "slug": "dinosaurs-word-search",
        "title": "Dinosaurs & Fossils Word Search",
        "subtitle": "Prehistoric puzzles for dino enthusiasts",
        "color": (52, 48, 32),
        "puzzles": [
            Puzzle("Famous Dinosaurs", ["TREX", "TRICERATOPS", "VELOCIRAPTOR", "STEGOSAURUS", "DIPLODOCUS", "BRONTOSAUR", "PTERANODON", "ANKYLOSAURUS", "SPINOSAURUS", "ALLOSAURUS", "RAPTOR", "IGUANODON"]),
            Puzzle("Dino Features", ["FOSSIL", "SKELETON", "CLAW", "HORN", "TAIL", "TEETH", "ARMOR", "FEATHER", "SCALE", "BONE", "FRILL", "SPINE"]),
            Puzzle("Prehistoric World", ["JURASSIC", "TRIASSIC", "CRETACEOUS", "PANGAEA", "VOLCANO", "METEOR", "SWAMP", "FERN", "LAVA", "CRATER", "CANYON", "ANCIENT"]),
            Puzzle("Herbivores", ["BRACHIOSAU", "TRICERATOPS", "STEGOSAURUS", "DIPLODOCUS", "PARASAUR", "IGUANODON", "ANKYLOSAURUS", "PACHYCEPH", "HADROSAURUS", "APATOSAUR", "MAIASAURA", "LAMBEOSAUR"]),
            Puzzle("Carnivores", ["TREX", "VELOCIRAPTOR", "SPINOSAURUS", "ALLOSAURUS", "CARNOTAURUS", "DILOPHOSAUR", "GIGANOTO", "DEINONYCHUS", "CERATOSAUR", "MEGALOSAUR", "COMPSOGNATH", "UTAHRAPTOR"]),
            Puzzle("Marine Reptiles", ["MOSASAURUS", "PLESIOSAURUS", "ICHTHYOSAUR", "ELASMOSAUR", "LIOPLEURODON", "KRONOSAURUS", "NOTHOSAURUS", "TYLOSAUR", "DUNKLEOSTEUS", "AMMONITE", "TRILOBITE", "NAUTILUS"]),
            Puzzle("Paleontology", ["EXCAVATION", "FOSSIL", "MUSEUM", "SKELETON", "DISCOVERY", "SPECIMEN", "LIMESTONE", "AMBER", "GEOLOGIST", "DATING", "LAYER", "SITE"]),
            Puzzle("Flying Reptiles", ["PTERANODON", "PTERODACTYL", "QUETZALCOAT", "DIMORPHODON", "RHAMPHORHY", "ANHANGUERA", "ORNITHOCHE", "TAPEJARA", "DSUNGARIPT", "NYCTOSAURUS", "TROPEOGNATH", "AERODACTYL"]),
            Puzzle("Dino Movies", ["JURASSIC", "PARK", "WORLD", "RAPTOR", "ISLAND", "KINGDOM", "DOMINION", "CRICHTON", "GRANT", "MALCOLM", "ELLIE", "HAMMOND"]),
            Puzzle("Extinction", ["ASTEROID", "IMPACT", "CRATER", "VOLCANO", "CLIMATE", "SURVIVE", "MAMMAL", "EVOLVE", "ADAPT", "FOSSIL", "THEORY", "EVIDENCE"]),
        ],
    },
    {
        "slug": "baby-shower-word-search",
        "title": "Baby Shower Word Search",
        "subtitle": "Sweet puzzles to celebrate new arrivals",
        "color": (72, 52, 60),
        "puzzles": [
            Puzzle("Baby Essentials", ["DIAPER", "BOTTLE", "PACIFIER", "CRIB", "BLANKET", "STROLLER", "ONESIE", "BIB", "RATTLE", "SWADDLE", "MONITOR", "CARRIER"]),
            Puzzle("Baby Names", ["OLIVIA", "LIAM", "EMMA", "NOAH", "AMELIA", "JAMES", "SOPHIA", "OLIVER", "CHARLOTTE", "ELIJAH", "AURORA", "LUCAS"]),
            Puzzle("Nursery", ["MOBILE", "ROCKER", "LAMP", "RUG", "MURAL", "SHELF", "CLOSET", "CURTAIN", "CUSHION", "BASKET", "TEDDY", "DECOR"]),
            Puzzle("Baby Milestones", ["CRAWL", "WALK", "SMILE", "LAUGH", "BABBLE", "TEETH", "ROLLOVER", "CLAP", "WAVE", "STAND", "GIGGLE", "GRASP"]),
            Puzzle("Pregnancy", ["TRIMESTER", "ULTRASOUND", "HEARTBEAT", "KICKING", "NURSERY", "SHOWER", "GENDER", "ANNOUNCE", "EXPECT", "GLOW", "BELLY", "BUMP"]),
            Puzzle("Baby Clothes", ["ONESIE", "BOOTIE", "BONNET", "ROMPER", "MITTEN", "SOCK", "DRESS", "SLEEPER", "JACKET", "HAT", "SWEATER", "OVERALL"]),
            Puzzle("Baby Animals", ["KITTEN", "PUPPY", "BUNNY", "DUCKLING", "LAMB", "FOAL", "CALF", "CHICK", "CUB", "FAWN", "JOEY", "PIGLET"]),
            Puzzle("Shower Games", ["BINGO", "TRIVIA", "GUESS", "RAFFLE", "ADVICE", "WISHES", "PREDICT", "MEASURE", "TASTE", "SCRAMBLE", "MATCH", "PRIZE"]),
            Puzzle("Bedtime", ["LULLABY", "STORY", "CUDDLE", "DREAM", "SLEEP", "ROCK", "STARS", "MOON", "NIGHT", "GENTLE", "QUIET", "COZY"]),
            Puzzle("Parenthood", ["LOVE", "JOY", "FAMILY", "CHERISH", "NURTURE", "PROTECT", "GUIDE", "PATIENCE", "LAUGHTER", "WONDER", "PRECIOUS", "BLESSED"]),
        ],
    },
    {
        "slug": "nursing-word-search",
        "title": "Nurses & Healthcare Word Search",
        "subtitle": "Puzzles for healthcare heroes",
        "color": (28, 52, 66),
        "puzzles": [
            Puzzle("Nursing Basics", ["PATIENT", "VITALS", "CHARTING", "ROUNDS", "TRIAGE", "ASSESS", "HANDOFF", "SCRUBS", "BADGE", "SHIFT", "STATION", "CALL"]),
            Puzzle("Medical Terms", ["DIAGNOSIS", "SYMPTOM", "TREATMENT", "PROGNOSIS", "ACUTE", "CHRONIC", "BENIGN", "STERILE", "DOSAGE", "CONSENT", "SUTURE", "BIOPSY"]),
            Puzzle("Hospital", ["EMERGENCY", "SURGERY", "PHARMACY", "RADIOLOGY", "WARD", "CLINIC", "LOBBY", "CHAPEL", "CAFETERIA", "NURSERY", "INTAKE", "DISCHARGE"]),
            Puzzle("Medical Tools", ["STETHOSCOPE", "SYRINGE", "BANDAGE", "THERMOMETER", "FORCEPS", "SCALPEL", "GAUZE", "CLAMP", "CATHETER", "GLOVES", "MASK", "GOWN"]),
            Puzzle("Specialties", ["PEDIATRIC", "CARDIAC", "ONCOLOGY", "NEONATAL", "SURGICAL", "GERIATRIC", "TRAUMA", "OBSTETRIC", "PSYCH", "HOSPICE", "REHAB", "DIALYSIS"]),
            Puzzle("Nurse Life", ["COMPASSION", "TEAMWORK", "OVERTIME", "COFFEE", "HEROES", "RESILIENT", "DEDICATE", "ADVOCATE", "SELFLESS", "STAMINA", "COURAGE", "HEART"]),
            Puzzle("First Aid", ["CPR", "SPLINT", "TOURNIQUET", "COMPRESS", "ICE", "ELEVATE", "WOUND", "BLEEDING", "AIRWAY", "RESCUE", "STABLE", "SHOCK"]),
            Puzzle("Body Systems", ["CARDIAC", "NERVOUS", "SKELETAL", "MUSCULAR", "DIGESTIVE", "LYMPHATIC", "ENDOCRINE", "IMMUNE", "URINARY", "VASCULAR", "HEPATIC", "RENAL"]),
            Puzzle("Medications", ["ANTIBIOTIC", "INSULIN", "MORPHINE", "ASPIRIN", "STEROID", "SEDATIVE", "VACCINE", "SALINE", "HEPARIN", "TYLENOL", "IBUPROFEN", "CODEINE"]),
            Puzzle("Wellness", ["HYDRATE", "REST", "EXERCISE", "NUTRITION", "MENTAL", "BALANCE", "PREVENT", "SCREEN", "CHECKUP", "HYGIENE", "SLEEP", "STRESS"]),
        ],
    },
    {
        "slug": "video-games-word-search",
        "title": "Video Games Word Search",
        "subtitle": "Level up with gaming puzzles",
        "color": (24, 28, 48),
        "puzzles": [
            Puzzle("Classic Games", ["MARIO", "ZELDA", "TETRIS", "PACMAN", "SONIC", "DONKEYKONG", "METROID", "MEGAMAN", "CASTLEVANIA", "GALAGA", "PONG", "ASTEROIDS"]),
            Puzzle("Game Genres", ["RPG", "SHOOTER", "PUZZLE", "RACING", "STRATEGY", "ADVENTURE", "PLATFORM", "STEALTH", "SANDBOX", "HORROR", "FIGHTING", "SURVIVAL"]),
            Puzzle("Gaming Gear", ["CONSOLE", "KEYBOARD", "MOUSE", "HEADSET", "MONITOR", "JOYSTICK", "GAMEPAD", "SPEAKER", "WEBCAM", "CHAIR", "DESKTOP", "SCREEN"]),
            Puzzle("Popular Games", ["MINECRAFT", "FORTNITE", "ROBLOX", "OVERWATCH", "SKYRIM", "HALO", "DESTINY", "FALLOUT", "BIOSHOCK", "PORTAL", "HALFLIFE", "DIABLO"]),
            Puzzle("Game Characters", ["LINK", "MARIO", "PIKACHU", "KRATOS", "MASTERCHIEF", "LARA", "SAMUS", "KIRBY", "SONIC", "CLOUD", "SNAKE", "YOSHI"]),
            Puzzle("Gaming Terms", ["RESPAWN", "LOOT", "QUEST", "BOSS", "LEVEL", "SPAWN", "BUFF", "NERF", "GRIND", "COMBO", "CLUTCH", "NOOB"]),
            Puzzle("Nintendo", ["SWITCH", "MARIO", "ZELDA", "POKEMON", "KIRBY", "SPLATOON", "SMASH", "METROID", "PIKMIN", "STARFOX", "YOSHI", "LUIGI"]),
            Puzzle("Game Worlds", ["HYRULE", "MUSHROOM", "RAPTURE", "SKYRIM", "AZEROTH", "MIDGAR", "TAMRIEL", "DREAMLAND", "ZEBES", "KANTO", "HOENN", "JOHTO"]),
            Puzzle("Multiplayer", ["ONLINE", "COOP", "LOBBY", "SERVER", "TEAM", "SQUAD", "MATCH", "RANKED", "PARTY", "CHAT", "GUILD", "STREAM"]),
            Puzzle("Retro Gaming", ["ARCADE", "PIXEL", "SPRITE", "CARTRIDGE", "JOYSTICK", "HIGHSCORE", "COIN", "LIVES", "WARP", "POWERUP", "BONUS", "CHEAT"]),
        ],
    },
    {
        "slug": "mythology-word-search",
        "title": "Greek Mythology Word Search",
        "subtitle": "Epic puzzles from ancient legends",
        "color": (56, 38, 24),
        "puzzles": [
            Puzzle("Olympian Gods", ["ZEUS", "HERA", "POSEIDON", "ATHENA", "APOLLO", "ARTEMIS", "ARES", "APHRODITE", "HERMES", "HEPHAESTUS", "DEMETER", "DIONYSUS"]),
            Puzzle("Greek Heroes", ["HERCULES", "ACHILLES", "ODYSSEUS", "PERSEUS", "THESEUS", "JASON", "ORPHEUS", "ATALANTA", "AJAX", "HECTOR", "PARIS", "HELEN"]),
            Puzzle("Mythical Creatures", ["MINOTAUR", "CENTAUR", "PHOENIX", "GRIFFIN", "HYDRA", "CERBERUS", "PEGASUS", "MEDUSA", "CYCLOPS", "SPHINX", "SIREN", "CHIMERA"]),
            Puzzle("The Odyssey", ["ITHACA", "ODYSSEUS", "PENELOPE", "CYCLOPS", "CIRCE", "CALYPSO", "POSEIDON", "ATHENA", "TROY", "SIREN", "SCYLLA", "VOYAGE"]),
            Puzzle("The Underworld", ["HADES", "PERSEPHONE", "STYX", "CHARON", "CERBERUS", "TARTARUS", "ELYSIUM", "ASPHODEL", "LETHE", "ACHERON", "EREBUS", "SHADE"]),
            Puzzle("Titans", ["KRONOS", "RHEA", "ATLAS", "PROMETHEUS", "OCEANUS", "HYPERION", "THEMIS", "MNEMOSYNE", "COEUS", "PHOEBE", "TETHYS", "THEIA"]),
            Puzzle("Greek Places", ["OLYMPUS", "ATHENS", "SPARTA", "TROY", "DELPHI", "CRETE", "CORINTH", "THEBES", "MYCENAE", "ARGOS", "ARCADIA", "ITHACA"]),
            Puzzle("Trojan War", ["ACHILLES", "HECTOR", "HELEN", "PARIS", "AGAMEMNON", "PRIAM", "AJAX", "ODYSSEUS", "MENELAUS", "TROJAN", "SHIELD", "ARROW"]),
            Puzzle("Powers And Magic", ["PROPHECY", "ORACLE", "NECTAR", "AMBROSIA", "THUNDER", "TRIDENT", "AEGIS", "LYRE", "CADUCEUS", "LAUREL", "GOLDEN", "IMMORTAL"]),
            Puzzle("Legends", ["LABYRINTH", "GOLDEN", "FLEECE", "PANDORA", "ICARUS", "DAEDALUS", "NARCISSUS", "MIDAS", "SISYPHUS", "TANTALUS", "ARACHNE", "ECHO"]),
        ],
    },
]
